apiVersion: v1
kind: Pod
metadata:
  name: busybox-jj
  labels:
    env: test
spec:
  containers:
  - name: busybox
    image: gelius7/docker-debug
    imagePullPolicy: IfNotPresent
    # command: [ "/bin/bash", "-c", "--" ]
    # args: [ "while true; do sleep 30; done;" ]
  # nodeSelector:
  #   kubernetes.io/hostname: ip-10-192-145-208.ap-northeast-2.compute.internal